config/routes.rb
WebmilEu::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  root to: 'pages#home'

  resources :works, only: [:index, :show], controller: :work

  get 'contacts' => 'contact#index', as: 'contacts'
  post 'contacts' => 'contact#create', as: 'contacts'

  match '/studio', to: 'pages#studio'

  match '/uk/index.html', to: redirect('http://webmil.com.ua')
  match '/uk/services.html', to: redirect('http://webmil.com.ua/studio')
  match '/uk/portfolio.html', to: redirect('http://webmil.com.ua/works')
  match '/uk/studio.html', to: redirect('http://webmil.com.ua/contacts')

  match '/en/index.html', to: redirect('http://webmil.eu')
  match '/en/services.html', to: redirect('http://webmil.eu/studio')
  match '/en/portfolio.html', to: redirect('http://webmil.eu/works')
  match '/en/studio.html', to: redirect('http://webmil.eu/contacts')

end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :subject, :body

  validates :name, :email, :subject, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  attr_accessible :image, :remove_image,  :image_cache, :image_asset, :title
  belongs_to :work, inverse_of: :pictures
  mount_uploader :image, ImageUploader
end
# == Schema Information
#
# Table name: pictures
#
#  id         :integer(4)      not null, primary key
#  image      :string(255)
#  title      :string(255)
#  work_id    :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable,
  		 :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end
# == Schema Information
#
# Table name: users
#
#  id                     :integer(4)      not null, primary key
#  email                  :string(255)     default(""), not null
#  encrypted_password     :string(255)     default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer(4)      default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime        not null
#  updated_at             :datetime        not null
#

app/models/work.rb
class Work < ActiveRecord::Base
  attr_accessible :description_en, :main_image, :remove_main_image,
  				  :main_image_cache, :main_image_asset, :name_en,
  				  :short_description_en, :slug, :url, :pictures_attributes, :order, :tag,
            :name_uk, :description_uk, :short_description_uk


  mount_uploader :main_image, MainImageUploader
  has_many :pictures, dependent: :destroy
  accepts_nested_attributes_for :pictures

  # validates_format_of :url, :with => URI::regexp
  validates :name_en, presence: true
  validates :slug, presence: true
  validates :url, presence: true

  def name
    self.send("name_#{I18n.locale}") || self.name_en
  end

  def description
    self.send("description_#{I18n.locale}") || self.description_en
  end

  def short_description
    self.send("short_description_#{I18n.locale}") || self.short_description_en
  end

  def full_url
  	"http://"+url
  end
end
# == Schema Information
#
# Table name: works
#
#  id                :integer(4)      not null, primary key
#  name              :string(255)
#  url               :string(255)
#  main_image        :string(255)
#  short_description :string(255)
#  description       :string(1000)
#  slug              :string(255)
#  created_at        :datetime        not null
#  updated_at        :datetime        not null
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contact_controller.rb
class ContactController < FrontendController
  before_filter :set_title

  def index
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])

    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      redirect_to(contacts_path, notice: t(:message_was_sent))
    else
      flash.now.alert = t(:fill_all_fields)
      render :index
    end
  end

  private
    def set_title
      @page_title = "- #{t(:contacts)}"
    end
end

app/controllers/frontend_controller.rb
class FrontendController < ApplicationController
  before_filter :set_locale

  private
    def set_locale
      parsed_locale = request.host.split('.').last.to_sym
      locale = :uk if [:ua, :uk].include? parsed_locale
      I18n.locale = locale || I18n.default_locale
    end
end

app/controllers/pages_controller.rb
class PagesController < FrontendController

  def home
  	@page_title = "- #{t(:home)}"
  end

  def studio
  	@page_title = "- #{t(:studio)}"
  end
end

app/controllers/work_controller.rb
class WorkController < FrontendController
  def index
   @page_title = "- #{t(:works)}"
   @works = Work.order("`order` desc").all

  end

  def show
   @work = Work.find_by_slug(params[:id])
   @page_title = "- #{@work.name}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/work_helper.rb
module WorkHelper
end

app/views/contact/index.html.haml
.container
  .top-txt
    %h2= t(:contact_us_title)
    %p= t(:description)
  .left-address
    .address{itemscope: true,  itemtype: "http://schema.org/Organization"}
      %meta{itemprop: "name", content: "Webmil"}
        %address{itemscope: true, itemprop: "address" ,itemtype: "http://schema.org/PostalAddress"}
          %h2.adress= t(:address)
          .locality{itemprop: "addressLocality"}
            %p= t(:address_first_line)
            %p= raw t(:address_second_line)
          .street{itemprop: "streetAddress"}
            %p= t(:address_third_line)
          %h2.phone= t(:phone)
          .tel
            %p{itemprop: "telephone"}= t(:contact_phone_main)
            %p{itemprop: "telephone"}= t(:contact_phone_second)
            %p{itemprop: "telephone"}= t(:contact_phone_third)

          %h2.on-line= t(:on_line)
          .skype
            %p
              = t(:skype)
              %span= t(:contact_skype)
          .mail
            %p
              = t(:e_mail)
              %span{itemprop: "email"}= t(:contact_email)
  .right-address
    %h2= t(:how_to_get)
    #map


%script{'type'=> 'text/javascript'}
  :plain
    //google map
    var init = function(){
        var myOptions = {
            zoom: 15,
            streetViewControl: false ,
            mapTypeId: google.maps.MapTypeId.ROADMAP};
        var map = new google.maps.Map(document.getElementById("map"), myOptions);
            var pinkParksStyles = [
                {
                    featureType: "all",
                    stylers: [
                        { hue: "#123fff" },
                        { saturation: "-100" },
                        { lightness: "0" },

                    ]
                },
                {
                    featureType: "road",
                    stylers: [
                        { hue: "#123000" },
                        { saturation: "-100" }
                    ]
                }
            ];
    map.setOptions({styles: pinkParksStyles});
        var geocoder = new google.maps.Geocoder();
        geocoder.geocode( { 'address': 'Івано-Франківськ, Січових Стрільців 34'}, function(results, status){
            if (status == google.maps.GeocoderStatus.OK){
                map.setCenter(results[0].geometry.location);
                var conf ={
                    map: map,
                    position: results[0].geometry.location};
                var marker = new google.maps.Marker(conf);
            }
        })
    };
    google.maps.event.addDomListener(window, 'load', init());

app/views/layouts/_footer.html.haml
%footer
  .footer-container
    .sitemap
      %h4= t(:sitemap)
      %ul
        %li
          = link_to t(:footer_home), root_path
          %p= t(:footer_home_desc)
        %li
          = link_to t(:footer_works), works_path
          %p= t(:footer_works_desc)
        %li
          = link_to t(:footer_team), studio_path
          %p= t(:footer_team_desc)
        %li
          = link_to t(:footer_contacts), contacts_path
          %p= t(:footer_contacts_desc)
      .copyright
        %p= t(:copyright)

    .resources
      %h4= t(:resources)
      %ul
        %li
          %a{:href => "http://facebook.com/webmileu"} facebook
        %li
          %a{:href => "http://twitter.com/webmil"} twitter
        %li
          %a{:href => "https://plus.google.com/105004848481490299912", :rel=>"publisher"} google+
    .address{itemscope: true,  itemtype: "http://schema.org/Organization"}
      %h4= t(:get_in_touch)
      %meta{itemprop: "name", content: "Webmil"}
      %address{itemscope: true, itemprop: "address" ,itemtype: "http://schema.org/PostalAddress"}
        .tel{itemprop: "telephone"}= t(:contact_phone_main)
        .mail{itemprop: "email"}= t(:contact_email)
      %p
        = link_to t(:map_directions), contacts_path
%script{'type'=> 'text/javascript'}
  :plain
    $(window).load(function(){
        $('.bw').BlackAndWhite({
            hoverEffect : true,
            // set the path to BnWWorker.js for a superfast implementation
            webworkerPath : false,
            // for the images with a fluid width and height
            responsive:true
        });
    });

    <!-- Yandex.Metrika counter -->
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter19172665 = new Ya.Metrika({id:19172665,
                        clickmap:true,
                        trackLinks:true,
                        accurateTrackBounce:true});
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");

app/views/layouts/_navigation.html.haml
.menu
  %nav
    %ul
      %li#home
        = active_link_to  t(:home), root_path
      %li#work
        = active_link_to t(:works), works_path
      %li#studio
        = active_link_to t(:studio), studio_path
      %li#contact
        = active_link_to t(:contacts), contacts_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"}
    %title Webmil #{@page_title}
    = stylesheet_link_tag 'screen', media: 'screen'
    = stylesheet_link_tag 'mobile', media: 'screen and (max-width: 330px),screen and (max-device-width: 330px)'
    = stylesheet_link_tag 'print', media: 'print'

    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=PT+Sans|PT+Sans+Narrow&subset=latin,cyrillic'
    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Marmelad&subset=latin,cyrillic,latin-ext'
    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Cuprum:400,700&subset=latin,latin-ext,cyrillic'

    /[if lt IE 9]
      = javascript_include_tag 'http://html5shiv.googlecode.com/svn/trunk/html5.js'
    = javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js'
    = javascript_include_tag 'http://maps.googleapis.com/maps/api/js?sensor=false'
    = javascript_include_tag 'jQuery.BlackAndWhite.min.js'
    = javascript_include_tag 'jquery.masonry.min.js'
    = javascript_include_tag 'center.js'
    <link href="https://plus.google.com/105004848481490299912" rel="publisher" />
  %body
    .wrap
      %header
        .header
          .left-side
            / .lang-list
            /   %ul
            /     %li
            /       %a.active.en{href: '#'} eng
            /     %li
            /       %a.ua{href: '#'} ua
            .slogan
              = image_tag(t(:slogan_img), alt: t(:slogan))
            = render 'layouts/navigation'
            .menu
          .logo
            = link_to image_tag('logo.png', alt: 'Webmil'), root_path

      =yield

      .footer-push
    = render 'layouts/footer'

app/views/pages/_clients.html.haml
%section
  .clients
    .list
      %h2= t(:clients)
      .bw
        = image_tag('clients/solidsocial.png', alt: 'Solid Social')
      .bw
        = image_tag('clients/lectrio.png', alt: 'Lectrio')
      .bw
        = image_tag('clients/razmir.png', alt: 'Razmir')
      .bw
        = image_tag('clients/canactions.png', alt: 'Canactions')
      .bw
        = image_tag('clients/expono.png', alt: 'Expono')

app/views/pages/home.html.haml
.container
  %section
    %article
      .about
        .logo
          =image_tag('11.png', alt: '', style: 'float: left;')
        .desc= t(:main_desc)
    %article
      .design
        .logo
          =image_tag('design.png', alt: t(:design))
        .desc
          %h2= t(:design)
          %p= t(:design_desc)
    %article
      .development
        .logo
          =image_tag('development.png', alt: t(:development))
        .desc
          %h2= t(:development)
          %p= t(:development_desc)
    %article
      .complex-websites
        .logo
          =image_tag('complex-websites.png', alt: t(:complex_apps))
        .desc
          %h2= t(:complex_apps)
          %p= t(:complex_apps_desc)
    %article
      .code-quality
        .logo
          =image_tag('code-quality.png', alt: t(:code_quality))
        .desc
          %h2= t(:code_quality)
          %p= t(:code_quality_desc)
.container
  = render 'pages/clients'

app/views/pages/studio.html.haml
.container
  %section
    %article
      .top-txt
        %h2= t(:about_us_header)
        %p= t(:about_us_desc)
  %section
    .team
      %h2= t(:team_header)
      %ul.employees
        %li.vcard
          =image_tag('team/denys.jpg', alt: t(:denys_photo), class: 'photo')
          %p.fn= t(:denys)
          %p.title= t(:developer)
          %span.org Webmil
        %li.vcard
          =image_tag('team/nikita.jpg', alt: t(:nikita_photo), class: 'photo')
          %p.fn= t(:nikita)
          %p.title= t(:designer)
          %span.org Webmil
        %li.vcard
          =image_tag('team/oleg.jpg', alt: t(:oleg_photo), class: 'photo')
          %p.fn= t(:oleg)
          %p.title= t(:developer)
          %span.org Webmil
        %li.vcard
          =image_tag('team/roman.jpg', alt: t(:roman_photo), class: 'photo')
          %p.fn= t(:roman)
          %p.title= t(:developer)
          %span.org Webmil
        %li.vcard
          =image_tag('team/rostyslav.jpg', alt: t(:rostyslav_photo), class: 'photo')
          %p.fn= t(:rostyslav)
          %p.title= t(:developer)
          %span.org Webmil
        %li.vcard
          =image_tag('team/sasha.jpg', alt: t(:sasha_photo), class: 'photo')
          %p.fn= t(:sasha)
          %p.title= t(:developer)
          %span.org Webmil
        %li.vcard
          =image_tag('team/sergij.jpg', alt: t(:sergij_photo), class: 'photo')
          %p.fn= t(:sergij)
          %p.title= t(:manager)
          %span.org Webmil
        %li.vcard
          =image_tag('team/victor.jpg', alt: t(:victor_photo), class: 'photo')
          %p.fn= t(:victor)
          %p.title= t(:developer)
          %span.org Webmil
        %li.vcard
          =image_tag('team/yura.png', alt: t(:yura_s_photo), class: 'photo')
          %p.fn= t(:yura_s)
          %p.title= t(:designer)
          %span.org Webmil
        %li.vcard
          =image_tag('team/yura_.jpg', alt: t(:yura_r_photo), class: 'photo')
          %p.fn= t(:yura_r)
          %p.title= t(:frontend_developer)
          %span.org Webmil
  = render 'pages/clients'

app/views/work/_listitem.html.haml
%li.box.bwWrapper
  %figure
    %a{href: 'work.html'}
      = image_tag("portfolio-#{rand(1..4)}.png", alt: 'Portfolio')
    %figcaption
      %div{class:"work-short-desc color-#{rand(1..4)}"}
        %p
          %a{href: 'work.html'} web site “Business Concept” company
        = link_to('http://bcu.kiev.ua', 'http://bcu.kiev.ua', class: 'link')

app/views/work/index.html.haml
.works
  %ul#container.clearfix

    - @works.each do |work|
      %li.box.bwWrapper
        %figure
          = link_to image_tag(work.main_image, alt: work.short_description), work_path(work.slug)
          %figcaption
            %div{class:"work-short-desc color-#{1+rand(4)}"}
              %p
                = link_to work.name, work_path(work.slug)
              = link_to work.url, work.full_url, class: 'link', target: '_blank'

.clearfix

%script{'type'=> 'text/javascript'}
  :plain
    $(document).ready(function() {
        $('#container').center();
        $(window).resize(function() {
            $('#container').center();
        });
        $('.work-short-desc').animate({backgroundColor: 'blue' }, "slow");
        var $container = $('#container');
        $container.imagesLoaded( function(){
            $container.masonry({
                itemSelector : '.box',
                isAnimated: true
            });
        });
    });
    $(window).load(function(){
        $('.bwWrapper').BlackAndWhite({
            hoverEffect : true,
            // set the path to BnWWorker.js for a superfast implementation
            webworkerPath : false,
            // for the images with a fluid width and height
            responsive:true
        });
    });

app/views/work/show.html.haml
.work-background
	.container
		.work
			%h2
				=@work.name
				= link_to t(:back), works_path, class: 'link'
			= link_to @work.url, @work.full_url, target: '_blank'
			-unless @work.tag?
				%p=@work.tag
			.description
				%p
					=@work.description
			.screenshots
				- @work.pictures.each do |picture|
					%img{src: picture.image.url, alt: picture.title}
	.container
	/ .advertising
	/ 	.booklet
	/ 		%img{src: 'images/work-3.png', alt: 'Work'}
	/ 	.city-light
	/ 		%img{src: 'images/work-4.png', alt: 'Work'}